### ISSUE TITLE
Dependency walk failed

### ISSUE THREAD

**Issue by smvsmv** [python-poetry/poetry-plugin-export#186] opened 2023-03-08 01:13 UTC
poetry export to requirements.txt fails with `Dependency walk failed at torch (>=1.6.0) error`

Any fix available? if not any workaround available?
 
Poetry (version 1.2.2)
System Version: macOS 13.2 (22D49)
Kernel Version: Darwin 22.3.0

pyproject.toml 
```
[tool.poetry.dependencies]
python = "^3.9.9"
torch = [
    {markers = "platform_machine == \"arm64\"", url = "https://download.pytorch.org/whl/cpu/torch-1.13.1-cp39-none-macosx_11_0_arm64.whl"},
    {markers= "platform_machine != \"arm64\"", url="https://download.pytorch.org/whl/torch-1.13.1-cp39-cp39-manylinux2014_aarch64.whl"}]
sentence-transformers = "2.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

the poetry.lock has 2 versions for torch "1.13.1" and torch = ">=1.6.0"

```
[package.source]
type = "url"
url = "https://download.pytorch.org/whl/cpu/torch-1.13.1-cp39-none-macosx_11_0_arm64.whl"
[[package]]
name = "torch"
version = "1.13.1"
description = "Tensors and Dynamic neural networks in Python with strong GPU acceleration"
category = "main"
optional = false
python-versions = ">=3.7.0"
```

and torch = ">=1.6.0" coming from sentence-transformers

```
[[package]]
name = "sentence-transformers"
version = "2.2.2"
description = "Multilingual text embeddings"
category = "main"
optional = false
python-versions = ">=3.6.0"

[package.dependencies]
huggingface-hub = ">=0.4.0"
nltk = "*"
numpy = "*"
scikit-learn = "*"
scipy = "*"
sentencepiece = "*"
torch = ">=1.6.0"
torchvision = "*"
tqdm = "*"
transformers = ">=4.6.0,<5.0.0"
```

**Comment by okojoalg** [comment] 2023-10-18 01:26
I encountered the same bug too.

part of pyproject.toml
```
[tool.poetry.dependencies]
python = ">=3.10,<3.11"
torch = [
    { platform = "darwin", url = "https://download.pytorch.org/whl/cpu/torch-2.1.0-cp310-none-macosx_11_0_arm64.whl" },
    { platform = "linux", url = "https://download.pytorch.org/whl/cu121/torch-2.1.0%2Bcu121-cp310-cp310-linux_x86_64.whl" }
]
torchvision = [
    { platform = "darwin", url = "https://download.pytorch.org/whl/cpu/torchvision-0.16.0-cp310-cp310-macosx_11_0_arm64.whl" },
    { platform = "linux", url = "https://download.pytorch.org/whl/cu121/torchvision-0.16.0%2Bcu121-cp310-cp310-linux_x86_64.whl" }
]
open-clip-torch = "^2.22.0"
```

then the exception is thrown if you run poetry export. But the exception is not thrown without lines containing darwin.

**Comment by happypgh** [comment] 2023-11-08 11:30
> I encountered the same bug too.
> 
> part of pyproject.toml
> 
> ```
> [tool.poetry.dependencies]
> python = ">=3.10,<3.11"
> torch = [
>     { platform = "darwin", url = "https://download.pytorch.org/whl/cpu/torch-2.1.0-cp310-none-macosx_11_0_arm64.whl" },
>     { platform = "linux", url = "https://download.pytorch.org/whl/cu121/torch-2.1.0%2Bcu121-cp310-cp310-linux_x86_64.whl" }
> ]
> torchvision = [
>     { platform = "darwin", url = "https://download.pytorch.org/whl/cpu/torchvision-0.16.0-cp310-cp310-macosx_11_0_arm64.whl" },
>     { platform = "linux", url = "https://download.pytorch.org/whl/cu121/torchvision-0.16.0%2Bcu121-cp310-cp310-linux_x86_64.whl" }
> ]
> open-clip-torch = "^2.22.0"
> ```
> 
> then the exception is thrown if you run poetry export. But the exception is not thrown without lines containing darwin.



> I encountered the same bug too.
> 
> part of pyproject.toml
> 
> ```
> [tool.poetry.dependencies]
> python = ">=3.10,<3.11"
> torch = [
>     { platform = "darwin", url = "https://download.pytorch.org/whl/cpu/torch-2.1.0-cp310-none-macosx_11_0_arm64.whl" },
>     { platform = "linux", url = "https://download.pytorch.org/whl/cu121/torch-2.1.0%2Bcu121-cp310-cp310-linux_x86_64.whl" }
> ]
> torchvision = [
>     { platform = "darwin", url = "https://download.pytorch.org/whl/cpu/torchvision-0.16.0-cp310-cp310-macosx_11_0_arm64.whl" },
>     { platform = "linux", url = "https://download.pytorch.org/whl/cu121/torchvision-0.16.0%2Bcu121-cp310-cp310-linux_x86_64.whl" }
> ]
> open-clip-torch = "^2.22.0"
> ```
> 
> then the exception is thrown if you run poetry export. But the exception is not thrown without lines containing darwin.

I'm having the same issue with the same dependency structure for torch and torchvision like yours

**Comment by gflatters** [comment] 2024-01-09 14:13
I found a workaround for my use case which is to make the darwin wheel a dev dependency so that only the linux wheel gets exported to the requirements.txt file.

**Comment by gflatters** [comment] 2024-01-09 14:58
I was running into this issue when building my docker image, setting the platform flag fixed it for me.

**Comment by radoering** [comment] 2024-03-15 14:07
Duplicate of #183

**Closed by radoering** 2024-03-15 14:07 UTC
