### ISSUE TITLE
Dependency walk failed at requests (>=2.0.0)

### ISSUE THREAD

**Issue by Godcodewriter** [python-poetry/poetry-plugin-export#266] opened 2024-03-13 09:09 UTC
### Description:
When attempting to export project dependencies using Poetry with the command poetry export -vvv -f requirements.txt, I encountered an error related to dependency resolution for the requests package. The error message indicates that the dependency walk failed specifically at the requests package with a version requirement of >=2.0.0.

### Error Message:
```
Source (poetry-lockfile): 1 packages found for requests 2.29.0
Source (poetry-lockfile): 1 packages found for requests >=2.31.0,<3.0.0
Source (poetry-lockfile): 1 packages found for requests-oauthlib >=1.3.1,<2.0.0

  Stack trace:

  13  ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\cleo\application.py:327 in run
       325│ 
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a

  12  ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\poetry\console\application.py:190 in _run
       188│         self._load_plugins(io)
       189│
     → 190│         exit_code: int = super()._run(io)
       191│         return exit_code
       192│

  11  ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\cleo\application.py:431 in _run
       429│             io.input.interactive(interactive)
       430│
     → 431│         exit_code = self._run_command(command, io)
       432│         self._running_command = None
       433│

  10  ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\cleo\application.py:473 in _run_command
       471│ 
       472│         if error is not None:
     → 473│             raise error
       474│
       475│         return terminate_event.exit_code

   9  ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\cleo\application.py:457 in _run_command
       455│ 
       456│             if command_event.command_should_run():
     → 457│                 exit_code = command.run(io)
       458│             else:
       459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

   8  ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\cleo\commands\base_command.py:117 in run
       115│         io.input.validate()
       116│
     → 117│         return self.execute(io) or 0
       118│
       119│     def merge_application_definition(self, merge_args: bool = True) -> None:

   7  ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\cleo\commands\command.py:61 in execute
        59│
        60│         try:
     →  61│             return self.handle()
        62│         except KeyboardInterrupt:
        63│             return 1

   6  ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\poetry\console\commands\export.py:21 in handle
        19│                 style="warning",
        20│             )
     →  21│         return super().handle()  # type: ignore[no-any-return]
        22│

   5  ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\poetry_plugin_export\command.py:125 in handle
       123│         exporter.with_credentials(self.option("with-credentials"))
       124│         exporter.with_urls(not self.option("without-urls"))
     → 125│         exporter.export(fmt, Path.cwd(), output or self.io)
       126│
       127│         return 0

   4  ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\poetry_plugin_export\exporter.py:81 in export
        79│             raise ValueError(f"Invalid export format: {fmt}")
        80│
     →  81│         getattr(self, self.EXPORT_METHODS[fmt])(cwd, output)
        82│
        83│     def _export_generic_txt(

   3  ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\poetry_plugin_export\exporter.py:96 in _export_generic_txt
        94│         )
        95│
     →  96│         for dependency_package in get_project_dependency_packages(
        97│             self._poetry.locker,
        98│             project_requires=root.all_requires,

   2  ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\poetry_plugin_export\walker.py:97 in get_project_dependency_packages
        95│         selected.append(dependency)
        96│
     →  97│     for package, dependency in get_project_dependencies(
        98│         project_requires=selected,
        99│         locked_packages=repository.packages,

   1  ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\poetry_plugin_export\walker.py:125 in get_project_dependencies
       123│         )
       124│
     → 125│     nested_dependencies = walk_dependencies(
       126│         dependencies=project_requires,
       127│         packages_by_name=packages_by_name,

  RuntimeError

  Dependency walk failed at requests (>=2.0.0)

  at ~\AppData\Local\pipx\pipx\venvs\poetry\Lib\site-packages\poetry_plugin_export\walker.py:155 in walk_dependencies
      151│             requirement, packages_by_name, nested_dependencies
      152│         )
      153│
      154│         if not locked_package:
    → 155│             raise RuntimeError(f"Dependency walk failed at {requirement}")
      156│
      157│         if requirement.extras:
      158│             locked_package = locked_package.with_features(requirement.extras)
      159│
```
### Steps to Reproduce:

Install Poetry and initialize a new project with the provided pyproject.toml configuration.
```
[tool.poetry]
name = "poetry-export-issue"
version = "0.1.0"
description = ""
authors = ["Vlad <buffox88@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7 || ^3.9 || ^3.11"
requests = [
    { version = "2.29.0", python = ">=3.7, <3.9" },
    { version = "^2.31.0", python = ">=3.9" }
]
requests-oauthlib = "^1.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
Run the command poetry export -vvv -f requirements.txt to export project dependencies.
Observe the error related to dependency resolution failure for the requests package.
Expected Behavior:
The poetry export command should successfully export project dependencies without encountering dependency resolution failures.

### Additionally
Tested on python3.7 and 3.11.
pyproject.toml configuration includes version constraints for the requests package.
Internet connection stability has been verified to ensure proper dependency resolution.
Attempted to update project dependencies using poetry update but the issue persists.
Please let me know if further information is required or if there are any specific troubleshooting steps to follow.

**Comment by golgor** [comment] 2024-03-15 10:26
I also got a similar issue that broke our docker builds in Github Actions. The new version 1.7.0 doesn't seem to be compatible with Poetry 1.7.1, maybe this is intended?

We are using `poetry self add poetry-plugin-export` in our dockerfile and the result is:
```bash
12.25 Because no versions of poetry-plugin-export match >1.7.0,<2.0.0
12.25  and poetry-plugin-export (1.7.0) depends on poetry (>=1.8.0,<2.0.0), poetry-plugin-export (>=1.7.0,<2.0.0) requires poetry (>=1.8.0,<2.0.0).
12.25 So, because poetry-instance depends on both poetry (1.7.1) and poetry-plugin-export (^1.7.0), version solving failed.
```

**Comment by radoering** [comment] 2024-03-15 14:10
> I also got a similar issue that broke our docker builds in Github Actions. The new version 1.7.0 doesn't seem to be compatible with Poetry 1.7.1, maybe this is intended?

Yes, see the [release notes](https://github.com/python-poetry/poetry-plugin-export/releases/tag/1.7.0).

Duplicate of #183

**Closed by radoering** 2024-03-15 14:10 UTC

**Comment by Godcodewriter** [comment] 2024-03-18 09:04
> > I also got a similar issue that broke our docker builds in Github Actions. The new version 1.7.0 doesn't seem to be compatible with Poetry 1.7.1, maybe this is intended?
> 
> Yes, see the [release notes](https://github.com/python-poetry/poetry-plugin-export/releases/tag/1.7.0).
> 
> Duplicate of #183

poetry is already in the latest version 1.8.2, so I believe this is should be a new issue and I can still reproduce it.

**Comment by dimbleby** [comment] 2024-03-18 09:06
#183 is still open, there is no need to open yet another duplicate

**Comment by Godcodewriter** [comment] 2024-03-18 09:52
Now I see. 😅 Thank you.
